### ISSUE TITLE
Usage with Vite

### ISSUE THREAD

**Issue by clibu** [maxmilton/esbuild-minify-templates#194]
Any idea if it possible to use this plugin with Vite, which uses esbuild.

In vite.config.js I tried:
````
export default defineConfig({
    esbuild: {
        plugins: [minifyTemplates(), writeFiles()]
    }
})
````
But get the following error:
````
[vite:esbuild-transpile] Transform failed with 1 error:
c:\webapps\clibuNotes\node_modules\esbuild\lib\main.js:257:12: ERROR: Invalid option in transform() call: "plugins"
````

I've searched Vite issues and found [this](https://github.com/vitejs/vite/issues/2238) so it seems running esbuild plugins may not be possible.

**Comment by maxmilton** [comment]
As far as I know Vite only supports rollup style plugins. `esbuild-minify-templates` is an esbuild plugin and wasn't designed with Vite in mind. It's even somewhat hacky to get working with esbuild.

Since Vite supports rollup plugins, why not use an existing rollup plugin which has similar features? You can find a bunch by searching on GitHub: <https://github.com/search?q=rollup+plugin+minify+literal>, or NPM: <https://www.npmjs.com/search?q=rollup%20minify%20literal>.

Alternatively you could write your own rollup plugin and reuse code from this repo. Rollup plugins are easier to write than you might think!

- https://rollupjs.org/guide/en/#plugin-development
- https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility
